version: '3.8'

services:
  catho-scraper:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - scraper-data:/app/data
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
      - PYTHONUNBUFFERED=1
    secrets:
      - catho_email
      - catho_password
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

volumes:
  scraper-data:

secrets:
  catho_email:
    external: true
  catho_password:
    external: true
