version: '3.8'
services:
  catho-scraper:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - scraper-data:/app/data
    environment:
      - FLASK_ENV=production
      - EMAIL=${EMAIL}  # Configure no Portainer
      - SENHA=${SENHA}
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.catho.rule=Host(`catho.seudominio.com`)"

volumes:
  scraper-data:
